databases:
  - name: radical_DB
    databaseName: radical_db
    user: radical
    region: singapore

services:
  - type: web
    name: radical
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: radical_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
